server:
  port: 8080
spring:
  datasource:
    platform: mysql                        # 指定数据源类型
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-qdrtestdataww.mysql.rds.aliyuncs.com:3306/qidarenweb?useSSL=false
    username: root
    password: IELW1uE09Kbp4tVfj9Vo
    maxActive: 90
    maxIdle: 60
    minIdle: 30
    initialSize: 30
    testWhileIdle: true
    removeAbandoned: true
    logAbandoned: true 
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  resources:
    add-mappings: false
  cloud:
    bus:
     enabled: false
ctgmq:    #MQ配置
  enable: false
  #mybatis
mybatis:
  configLocation: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
